version: '3.8'

services:
  backend:
    build: 
      context: ./guidance-application
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./guidance-application/guidance_system.db:/app/guidance_system.db
      - ./guidance-application/uploads:/app/uploads
      - ./guidance-application/results:/app/results
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./guidance-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped 